create table person
(
    id   integer generated by default as identity
        primary key,
    name varchar(100) not null
        unique,
    age  integer
        constraint person_age_check
            check (age > 0)
);

INSERT INTO public.person (id, name, age) VALUES (1, 'Владимир', 2005);
INSERT INTO public.person (id, name, age) VALUES (2, 'Анастасия', 2005);
INSERT INTO public.person (id, name, age) VALUES (3, 'Алексей', 2001);
INSERT INTO public.person (id, name, age) VALUES (4, 'Никита', 2004);
INSERT INTO public.person (id, name, age) VALUES (5, 'Валерий', 2004);
INSERT INTO public.person (id, name, age) VALUES (6, 'Ольга', 2003);
INSERT INTO public.person (id, name, age) VALUES (7, 'Ксения', 2003);
INSERT INTO public.person (id, name, age) VALUES (8, 'Сергей', 2010);
INSERT INTO public.person (id, name, age) VALUES (9, 'Дмитрий', 2005);
INSERT INTO public.person (id, name, age) VALUES (10, 'Вениамин', 2003);
INSERT INTO public.person (id, name, age) VALUES (11, 'Ирина', 2002);
INSERT INTO public.person (id, name, age) VALUES (12, 'Михаил', 2004);
INSERT INTO public.person (id, name, age) VALUES (13, 'Евгений', 2000);


create table book
(
    book_id         integer generated by default as identity
        primary key,
    name            varchar(100) not null,
    author          varchar(30),
    year_of_writing integer
        constraint book_year_of_writing_check
            check (year_of_writing > 1200),
    book_owner_id   integer
        references person,
    taken_at        timestamp
);

INSERT INTO public.book (book_id, name, author, year_of_writing, book_owner_id, taken_at) VALUES (2, 'Книга 1', 'Автор 1', 1250, null, null);
INSERT INTO public.book (book_id, name, author, year_of_writing, book_owner_id, taken_at) VALUES (1, 'ABC', 'School', 2005, 10, null);
INSERT INTO public.book (book_id, name, author, year_of_writing, book_owner_id, taken_at) VALUES (4, 'Философия Java', 'Брюс Эккель', 2024, 10, null);
INSERT INTO public.book (book_id, name, author, year_of_writing, book_owner_id, taken_at) VALUES (3, 'Метафизика', 'Аристотель', 1201, 10, null);
INSERT INTO public.book (book_id, name, author, year_of_writing, book_owner_id, taken_at) VALUES (5, 'Книга 2', 'Автор 2', 1500, 10, null);
INSERT INTO public.book (book_id, name, author, year_of_writing, book_owner_id, taken_at) VALUES (6, 'Book3', 'Author3', 2000, null, null);
INSERT INTO public.book (book_id, name, author, year_of_writing, book_owner_id, taken_at) VALUES (7, 'Основы компьютерной графики: 3D-моделирование и 3D-печать', 'Владимир Лисяк', 2024, 13, '2025-01-21 13:43:39.331000');
